name: 'ci'

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: npm install
      - name: "Build package"
        run: npm run build
      - name: "Format files"
        run: npm run format
      - name: "Run linter"
        run: npm run lint
      - name: "Run tests"
        run: npm run package
      - name: "Package binaries"
        run: npm run package
      - name: "Test action"
        uses: ./
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          milestone: 'Test Milestone'
